spring:
  application:
    name: myjobsearch
  datasource:
    url: jdbc:mysql://localhost:3306/myjobsearch?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: arafin
    password: arafinN@121213
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  error:
    include-stacktrace: always
  compression:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE